import Fastify from 'fastify';
import helmet from '@fastify/helmet';
import cors from '@fastify/cors';
import jwt from '@fastify/jwt';
import rateLimit from '@fastify/rate-limit';
import multipart from '@fastify/multipart';
import { env } from './config/env.js';
import { authRoutes } from './modules/auth/routes.js';
import { dataRoutes } from './modules/data/routes.js';
import { adminRoutes } from './modules/admin/routes.js';
const app = Fastify({ logger: true });
await app.register(helmet);
await app.register(cors, { origin: true, credentials: true });
await app.register(rateLimit, { max: 100, timeWindow: '1 minute' });
await app.register(jwt, { secret: env.JWT_SECRET });
await app.register(multipart);
app.get('/health', async ()=>({ok:true}));
app.register(authRoutes,{prefix:'/api/auth'});
app.register(dataRoutes,{prefix:'/api/data'});
app.register(adminRoutes,{prefix:'/api/admin'});
app.listen({port:Number(env.PORT),host:'0.0.0.0'});
